### PR TITLE
4.0.0: Fix for Atom 1.0, use TextMate naming conventions, allowing themes to colour the statements and fixes #4.

### LINKED ISSUE #4: Is broken
I think this package might be broken. It's installed, but it's not even listed as a grammar :P

### PR DESCRIPTION
**Pull request by ghost**
Might not be perfect, but it's a start and I have ported what was there before and attempted to add string colouring as well. Have named 4.0.0 as the changes are quite major - Colours have changed, I have re-structured the project and used TextMate naming conventions.

I haven't tested the snippets, but they seem to work fine as is and therefore haven't made any changes there.

Fixes #4.

### CODE REVIEW

**Comment by xbony2** [comment]
Bump?

**Comment by xbony2** [comment]
Add the "as" keyword btw.

**Comment by elifoster** [comment]
Okay so for future reference, in case you decide to make an atom package or something, never update the version in package.json manually. That happens automatically when you push a new build.

**Comment by elifoster** [comment]
@Nentify So I'm looking at the source, and I'm sort of confused as to why the LESS file was deleted. Could you give me the documentation describing this change? I don't understand why the package, and like every other syntax theme package, actually works without it. I'm trying to test some stuff in dev mode, and, even when just adding things to the existing grammars, such as keyword.control.minetweaker, nothing is changing.

**Comment by ghost** [comment]
It's based on TextMate language grammars. It also means the package will follow whatever theme the user has selected. https://manual.macromates.com/en/language_grammars

**Pull request merged**
